Repository DunaevViktor/VJV-Survey, pull requests merged in 2020-12, with the labels that each got.

#1 docs: add objects metadata
  force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
  force-app/main/default/objects/Answer__c/fields/Body__c.field-meta.xml
  force-app/main/default/objects/Answer__c/fields/Group_Answer__c.field-meta.xml
  force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
  force-app/main/default/objects/Answer__c/fields/Value__c.field-meta.xml
  force-app/main/default/objects/Group_Answer__c/Group_Answer__c.object-meta.xml
  force-app/main/default/objects/Group_Answer__c/fields/IsLinked__c.field-meta.xml
  force-app/main/default/objects/Group_Answer__c/fields/Related_To__c.field-meta.xml
  force-app/main/default/objects/Group_Answer__c/fields/Survey__c.field-meta.xml
  force-app/main/default/objects/Question_Option__c/Question_Option__c.object-meta.xml
  force-app/main/default/objects/Question_Option__c/fields/Question__c.field-meta.xml
  force-app/main/default/objects/Question_Option__c/fields/Value__c.field-meta.xml
  force-app/main/default/objects/Question__c/Question__c.object-meta.xml
  force-app/main/default/objects/Question__c/fields/IsReusable__c.field-meta.xml
  force-app/main/default/objects/Question__c/fields/IsVisible__c.field-meta.xml
  force-app/main/default/objects/Question__c/fields/Label__c.field-meta.xml
  force-app/main/default/objects/Question__c/fields/Position__c.field-meta.xml
  force-app/main/default/objects/Question__c/fields/Required__c.field-meta.xml
  force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
  force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
  force-app/main/default/objects/Related_Object__c/Related_Object__c.object-meta.xml
  force-app/main/default/objects/Related_Object__c/fields/Related_Case__c.field-meta.xml
  force-app/main/default/objects/Related_Object__c/fields/Related_Contact__c.field-meta.xml
  force-app/main/default/objects/Related_Object__c/fields/Related_Lead__c.field-meta.xml
  force-app/main/default/objects/Survey_Email_Log__c/Survey_Email_Log__c.object-meta.xml
  force-app/main/default/objects/Survey_Email_Log__c/fields/Email__c.field-meta.xml
  force-app/main/default/objects/Survey_Email_Log__c/fields/Survey__c.field-meta.xml
  force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
  force-app/main/default/objects/Survey__c/fields/Description__c.field-meta.xml
  force-app/main/default/objects/Survey__c/fields/IsStandard__c.field-meta.xml
  force-app/main/default/objects/Survey__c/fields/Logo__c.field-meta.xml
  force-app/main/default/objects/Survey__c/fields/Related_To__c.field-meta.xml
  force-app/main/default/objects/Survey__c/fields/URL__c.field-meta.xml
  force-app/main/default/objects/Validation__c/Validation__c.object-meta.xml
  force-app/main/default/objects/Validation__c/fields/Condition__c.field-meta.xml
  force-app/main/default/objects/Validation__c/fields/Dependent_Question__c.field-meta.xml
  force-app/main/default/objects/Validation__c/fields/Related_Question__c.field-meta.xml
  manifest/package.xml
Labels: documentation

#3 docs: add permission set metadata
  force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
  force-app/main/default/permissionsets/Survey_Permission_Set.permissionset-meta.xml
  manifest/package.xml
Labels: bug, documentation

#4 docs: add object page layouts metadata
  force-app/main/default/layouts/Answer__c-Answer Layout.layout-meta.xml
  force-app/main/default/layouts/Group_Answer__c-Group Answer Layout.layout-meta.xml
  force-app/main/default/layouts/Question_Option__c-Question Option Layout.layout-meta.xml
  force-app/main/default/layouts/Question__c-Question Layout.layout-meta.xml
  force-app/main/default/layouts/Related_Object__c-Related Object Layout.layout-meta.xml
  force-app/main/default/layouts/Survey_Email_Log__c-Survey Email Log Layout.layout-meta.xml
  force-app/main/default/layouts/Survey__c-Survey Layout.layout-meta.xml
  force-app/main/default/layouts/Validation__c-Validation Layout.layout-meta.xml
  manifest/package.xml
Labels: documentation

#5 Feature/ASP-2
  force-app/main/default/flowDefinitions/Survey_Flow.flowDefinition-meta.xml
  force-app/main/default/flows/Survey_Flow.flow-meta.xml
  force-app/main/default/objects/Question__c/Question__c.object-meta.xml
  force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
  force-app/main/default/objects/Validation__c/Validation__c.object-meta.xml
  manifest/package.xml
Labels: documentation

#6 Documentation/ASP-19
  force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
  force-app/main/default/objects/Answer__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Group_Answer__c/Group_Answer__c.object-meta.xml
  force-app/main/default/objects/Group_Answer__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Question_Option__c/Question_Option__c.object-meta.xml
  force-app/main/default/objects/Question_Option__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Question__c/Question__c.object-meta.xml
  force-app/main/default/objects/Question__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Related_Object__c/Related_Object__c.object-meta.xml
  force-app/main/default/objects/Related_Object__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Survey_Email_Log__c/Survey_Email_Log__c.object-meta.xml
  force-app/main/default/objects/Survey_Email_Log__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
  force-app/main/default/objects/Survey__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Validation__c/Validation__c.object-meta.xml
  force-app/main/default/objects/Validation__c/listViews/All.listView-meta.xml
Labels: metadata

#8 docs: add Trigger Rule object metadata - 1
  force-app/main/default/layouts/Trigger_Rule__c-Trigger Rule Layout.layout-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/Trigger_Rule__c.object-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/fields/Field_Name__c.field-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/fields/Field_Value__c.field-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/fields/Object_Api_Name__c.field-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/fields/Operator__c.field-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/fields/Survey__c.field-meta.xml
  force-app/main/default/permissionsets/Survey_Permission_Set.permissionset-meta.xml
  manifest/package.xml
Labels: metadata

#9 docs: update metadata for tabs
  force-app/main/default/objects/Trigger_Rule__c/Trigger_Rule__c.object-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/listViews/All.listView-meta.xml
  force-app/main/default/tabs/Answer__c.tab-meta.xml
  force-app/main/default/tabs/Group_Answer__c.tab-meta.xml
  force-app/main/default/tabs/Question_Option__c.tab-meta.xml
  force-app/main/default/tabs/Question__c.tab-meta.xml
  force-app/main/default/tabs/Related_Object__c.tab-meta.xml
  force-app/main/default/tabs/Survey_Email_Log__c.tab-meta.xml
  force-app/main/default/tabs/Survey__c.tab-meta.xml
  force-app/main/default/tabs/Trigger_Rule__c.tab-meta.xml
  force-app/main/default/tabs/Validation__c.tab-meta.xml
  manifest/package.xml
Labels: bug, metadata

#10 fix: update tabs permissions
  force-app/main/default/permissionsets/Survey_Permission_Set.permissionset-meta.xml
Labels: bug, documentation, metadata

#12 docs: add global value set metadata
  force-app/main/default/globalValueSets/SurveyRuleObjects.globalValueSet-meta.xml
Labels: documentation

#13 docs: add configs for Email Receiver object
  README.md
  force-app/main/default/flowDefinitions/Case_Survey_Initiator.flowDefinition-meta.xml
  force-app/main/default/flowDefinitions/Contact_Survey_Initiator.flowDefinition-meta.xml
  force-app/main/default/flowDefinitions/Lead_Survey_Initiator.flowDefinition-meta.xml
  force-app/main/default/flows/Case_Survey_Initiator.flow-meta.xml
  force-app/main/default/flows/Contact_Survey_Initiator.flow-meta.xml
  force-app/main/default/flows/Lead_Survey_Initiator.flow-meta.xml
  force-app/main/default/globalValueSets/Object_Api_Names.globalValueSet-meta.xml
  force-app/main/default/layouts/Email_Receiver__c-Email Receiver Layout.layout-meta.xml
  force-app/main/default/layouts/Survey__c-Survey Layout.layout-meta.xml
  force-app/main/default/layouts/Trigger_Rule__c-Trigger Rule Layout.layout-meta.xml
  force-app/main/default/objects/Email_Receiver__c/Email_Receiver__c.object-meta.xml
  force-app/main/default/objects/Email_Receiver__c/fields/IsSend__c.field-meta.xml
  force-app/main/default/objects/Email_Receiver__c/fields/Survey__c.field-meta.xml
  force-app/main/default/objects/Email_Receiver__c/fields/Type__c.field-meta.xml
  force-app/main/default/objects/Email_Receiver__c/fields/Value__c.field-meta.xml
  force-app/main/default/objects/Email_Receiver__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/fields/Object_Api_Name__c.field-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/fields/Operator__c.field-meta.xml
  force-app/main/default/permissionsets/Survey_Permission_Set.permissionset-meta.xml
  force-app/main/default/tabs/Email_Receiver__c.tab-meta.xml
  force-app/main/default/tabs/Survey_Email_Log__c.tab-meta.xml
  manifest/package.xml
Labels: bug, documentation, metadata

#15 Feature/ASP-9-1
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreen.cmp
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreen.cmp-meta.xml
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreen.design
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreenController.js
  force-app/main/default/classes/QuestionController.cls
  force-app/main/default/classes/QuestionController.cls-meta.xml
  force-app/main/default/classes/QuestionControllerTest.cls
  force-app/main/default/classes/QuestionControllerTest.cls-meta.xml
  force-app/main/default/lwc/optionListElement/optionListElement.html
  force-app/main/default/lwc/optionListElement/optionListElement.js
  force-app/main/default/lwc/optionListElement/optionListElement.js-meta.xml
  force-app/main/default/lwc/questionBuilderScreenBody/questionBuilderScreenBody.css
  force-app/main/default/lwc/questionBuilderScreenBody/questionBuilderScreenBody.html
  force-app/main/default/lwc/questionBuilderScreenBody/questionBuilderScreenBody.js
  force-app/main/default/lwc/questionBuilderScreenBody/questionBuilderScreenBody.js-meta.xml
  force-app/main/default/lwc/questionCard/questionCard.html
  force-app/main/default/lwc/questionCard/questionCard.js
  force-app/main/default/lwc/questionCard/questionCard.js-meta.xml
  force-app/main/default/lwc/questionForm/questionForm.html
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionForm/questionForm.js-meta.xml
  force-app/main/default/lwc/questionSearch/questionSearch.css
  force-app/main/default/lwc/questionSearch/questionSearch.html
  force-app/main/default/lwc/questionSearch/questionSearch.js
  force-app/main/default/lwc/questionSearch/questionSearch.js-meta.xml
  force-app/main/default/objects/Question__c/fields/IsVisible__c.field-meta.xml
  force-app/main/default/staticresources/ArrowDownIcon.png
  force-app/main/default/staticresources/ArrowDownIcon.resource-meta.xml
  force-app/main/default/staticresources/ArrowUpIcon.png
  force-app/main/default/staticresources/ArrowUpIcon.resource-meta.xml
  force-app/main/default/staticresources/DeleteIcon.png
  force-app/main/default/staticresources/DeleteIcon.resource-meta.xml
  force-app/main/default/staticresources/EditIcon.png
  force-app/main/default/staticresources/EditIcon.resource-meta.xml
Labels: enhancement

#16 Feature/asp 28
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreen.cmp
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreen.design
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreenController.js
  force-app/main/default/classes/QuestionController.cls
  force-app/main/default/classes/QuestionControllerTest.cls
  force-app/main/default/classes/SurveyController.cls
  force-app/main/default/classes/SurveyController.cls-meta.xml
  force-app/main/default/classes/SurveyControllerTest.cls
  force-app/main/default/classes/SurveyControllerTest.cls-meta.xml
  force-app/main/default/lwc/questionBuilderScreenBody/questionBuilderScreenBody.html
  force-app/main/default/lwc/questionBuilderScreenBody/questionBuilderScreenBody.js
  force-app/main/default/lwc/questionCard/questionCard.html
  force-app/main/default/lwc/questionForm/questionForm.html
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionSearch/questionSearch.html
  force-app/main/default/lwc/questionSearch/questionSearch.js
  force-app/main/default/lwc/questionSearchItem/questionSearchItem.html
  force-app/main/default/lwc/questionSearchItem/questionSearchItem.js
  force-app/main/default/lwc/questionSearchItem/questionSearchItem.js-meta.xml
Labels: enhancement
