Repository DunaevViktor/VJV-Survey, pull requests merged in 2021-01, with the labels that each got.

#20 docs: update options global value set
  force-app/main/default/globalValueSets/Operators.globalValueSet-meta.xml
Labels: metadata

#21 Feature/asp 27
  force-app/main/default/aura/validationBuilderScreen/validationBuilderScreen.cmp
  force-app/main/default/aura/validationBuilderScreen/validationBuilderScreen.cmp-meta.xml
  force-app/main/default/aura/validationBuilderScreen/validationBuilderScreen.design
  force-app/main/default/aura/validationBuilderScreen/validationBuilderScreenController.js
  force-app/main/default/classes/ValidationController.cls
  force-app/main/default/classes/ValidationController.cls-meta.xml
  force-app/main/default/classes/ValidationControllerTest.cls
  force-app/main/default/classes/ValidationControllerTest.cls-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/validationBuilderScreenBody/validationBuilderScreenBody.html
  force-app/main/default/lwc/validationBuilderScreenBody/validationBuilderScreenBody.js
  force-app/main/default/lwc/validationBuilderScreenBody/validationBuilderScreenBody.js-meta.xml
  force-app/main/default/lwc/validationCard/validationCard.css
  force-app/main/default/lwc/validationCard/validationCard.html
  force-app/main/default/lwc/validationCard/validationCard.js
  force-app/main/default/lwc/validationCard/validationCard.js-meta.xml
  force-app/main/default/lwc/validationForm/validationForm.html
  force-app/main/default/lwc/validationForm/validationForm.js
  force-app/main/default/lwc/validationForm/validationForm.js-meta.xml
  force-app/main/default/lwc/validationForm/validationFormHelper.js
  force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
  manifest/package.xml
  package-lock.json
  package.json
Labels: enhancement

#19 Feature/asp 7
  force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapper.cmp
  force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapper.cmp-meta.xml
  force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapper.design
  force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapperController.js
  force-app/main/default/classes/LookupController.cls
  force-app/main/default/classes/LookupController.cls-meta.xml
  force-app/main/default/classes/LookupControllerTest.cls
  force-app/main/default/classes/LookupControllerTest.cls-meta.xml
  force-app/main/default/classes/MetadataFetcher.cls
  force-app/main/default/classes/MetadataFetcher.cls-meta.xml
  force-app/main/default/classes/MetadataFetcherTest.cls
  force-app/main/default/classes/MetadataFetcherTest.cls-meta.xml
  force-app/main/default/classes/TriggerRuleController.cls
  force-app/main/default/classes/TriggerRuleController.cls-meta.xml
  force-app/main/default/classes/TriggerRuleControllerTest.cls
  force-app/main/default/classes/TriggerRuleControllerTest.cls-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/customLookup/customLookup.html
  force-app/main/default/lwc/customLookup/customLookup.js
  force-app/main/default/lwc/customLookup/customLookup.js-meta.xml
  force-app/main/default/lwc/singleTriggerRule/helper.js
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.html
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js-meta.xml
  force-app/main/default/lwc/triggerRulesFooterNavigation/triggerRulesFooterNavigation.html
  force-app/main/default/lwc/triggerRulesFooterNavigation/triggerRulesFooterNavigation.js
  force-app/main/default/lwc/triggerRulesFooterNavigation/triggerRulesFooterNavigation.js-meta.xml
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.html
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js-meta.xml
  package-lock.json
Labels: enhancement

#22 Feature/asp 33
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreen.cmp
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreenController.js
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/formUtil/formUtil.js
  force-app/main/default/lwc/formUtil/formUtil.js-meta.xml
  force-app/main/default/lwc/optionListElement/optionListElement.html
  force-app/main/default/lwc/optionListElement/optionListElement.js
  force-app/main/default/lwc/questionBuilderScreenBody/questionBuilderScreenBody.html
  force-app/main/default/lwc/questionBuilderScreenBody/questionBuilderScreenBody.js
  force-app/main/default/lwc/questionCard/questionCard.html
  force-app/main/default/lwc/questionCard/questionCard.js
  force-app/main/default/lwc/questionForm/questionForm.html
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionSearch/questionSearch.html
  force-app/main/default/lwc/questionSearch/questionSearch.js
  force-app/main/default/lwc/questionSearchItem/questionSearchItem.html
  force-app/main/default/lwc/questionSearchItem/questionSearchItem.js
  force-app/main/default/lwc/validationForm/validationForm.js
Labels: enhancement

#24 Refactor/asp 37
  force-app/main/default/classes/QuestionController.cls
  force-app/main/default/classes/QuestionControllerTest.cls
  force-app/main/default/classes/TriggerRuleController.cls
  force-app/main/default/classes/TriggerRuleController.cls-meta.xml
  force-app/main/default/classes/TriggerRuleControllerTest.cls
  force-app/main/default/classes/TriggerRuleControllerTest.cls-meta.xml
  force-app/main/default/classes/ValidationController.cls
  force-app/main/default/classes/ValidationController.cls-meta.xml
  force-app/main/default/classes/ValidationControllerTest.cls
  force-app/main/default/classes/ValidationControllerTest.cls-meta.xml
  force-app/main/default/lwc/customLookup/customLookup.html
  force-app/main/default/lwc/customLookup/customLookup.js
  force-app/main/default/lwc/formUtil/formUtil.js
  force-app/main/default/lwc/questionBuilderScreenBody/questionBuilderScreenBody.js
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/singleTriggerRule/helper.js
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js
  force-app/main/default/lwc/validationBuilderScreenBody/validationBuilderScreenBody.js
  force-app/main/default/lwc/validationForm/validationForm.js
Labels: refactor

#25 Feature/ASP-11
  force-app/main/default/classes/SendEmailLogic.cls
  force-app/main/default/classes/SendEmailLogic.cls-meta.xml
  force-app/main/default/classes/SendEmailLogicTest.cls
  force-app/main/default/classes/SendEmailLogicTest.cls-meta.xml
  force-app/main/default/email/SurveyTemplates/Main_Template.email
  force-app/main/default/email/SurveyTemplates/Main_Template.email-meta.xml
  force-app/main/default/layouts/Survey__c-Survey Layout.layout-meta.xml
  force-app/main/default/objects/SurveyEmailConfig__c/SurveyEmailConfig__c.object-meta.xml
  force-app/main/default/objects/SurveyEmailConfig__c/fields/Company_Config__c.field-meta.xml
  force-app/main/default/objects/SurveyEmailConfig__c/fields/Display_Name__c.field-meta.xml
  force-app/main/default/objects/SurveyEmailConfig__c/fields/Subject__c.field-meta.xml
  force-app/main/default/objects/SurveyEmailConfig__c/fields/Template_Name__c.field-meta.xml
  force-app/main/default/objects/SurveyEmailConfig__c/fields/Url_Config__c.field-meta.xml
  force-app/main/default/objects/Survey__c/fields/IsResending__c.field-meta.xml
  force-app/main/default/objects/Survey__c/listViews/All.listView-meta.xml
  force-app/main/default/permissionsets/Survey_Permission_Set.permissionset-meta.xml
  manifest/package.xml
Labels: enhancement

#26 fix: delete empty string
  force-app/main/default/lwc/customLookup/customLookup.html
Labels: bug, question

#28 Fix/ASP-11-1
  force-app/main/default/classes/SendEmailLogicTest.cls
Labels: bug

#30 Feature/asp 39
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreen.cmp
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreen.cmp-meta.xml
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreen.design
  force-app/main/default/aura/questionBuilderScreen/questionBuilderScreenController.js
  force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapper.cmp-meta.xml
  force-app/main/default/aura/validationBuilderScreen/validationBuilderScreen.cmp
  force-app/main/default/aura/validationBuilderScreen/validationBuilderScreen.cmp-meta.xml
  force-app/main/default/aura/validationBuilderScreen/validationBuilderScreen.design
  force-app/main/default/aura/validationBuilderScreen/validationBuilderScreenController.js
  force-app/main/default/classes/QuestionControllerTest.cls
  force-app/main/default/classes/SurveyControllerTest.cls
  force-app/main/default/classes/SurveySettingController.cls
  force-app/main/default/classes/SurveySettingController.cls-meta.xml
  force-app/main/default/classes/SurveySettingControllerTest.cls
  force-app/main/default/classes/SurveySettingControllerTest.cls-meta.xml
  force-app/main/default/lwc/formUtil/formUtil.js
  force-app/main/default/lwc/questionBuilderScreenBody/questionBuilderScreenBody.js
  force-app/main/default/lwc/questionBuilderScreenBody/questionBuilderScreenBody.js-meta.xml
  force-app/main/default/lwc/questionCard/icons.js
  force-app/main/default/lwc/questionCard/labels.js
  force-app/main/default/lwc/questionCard/questionCard.html
  force-app/main/default/lwc/questionCard/questionCard.js
  force-app/main/default/lwc/questionForm/labels.js
  force-app/main/default/lwc/questionForm/questionForm.html
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionForm/questionFormHelper.js
  force-app/main/default/lwc/questionScreen/labels.js
  force-app/main/default/lwc/questionScreen/questionScreen.css
  force-app/main/default/lwc/questionScreen/questionScreen.html
  force-app/main/default/lwc/questionScreen/questionScreen.js
  force-app/main/default/lwc/questionScreen/questionScreen.js-meta.xml
  force-app/main/default/lwc/questionScreen/questionScreenHelper.js
  force-app/main/default/lwc/singleTriggerRule/helper.js
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js-meta.xml
  force-app/main/default/lwc/validationBuilderScreenBody/validationBuilderScreenBody.js
  force-app/main/default/lwc/validationBuilderScreenBody/validationBuilderScreenBody.js-meta.xml
  force-app/main/default/lwc/validationCard/labels.js
  force-app/main/default/lwc/validationCard/validationCard.js
  force-app/main/default/lwc/validationForm/labels.js
  force-app/main/default/lwc/validationForm/validationForm.js
  force-app/main/default/lwc/validationForm/validationFormHelper.js
  force-app/main/default/lwc/validationScreen/labels.js
  force-app/main/default/lwc/validationScreen/validationScreen.html
  force-app/main/default/lwc/validationScreen/validationScreen.js
  force-app/main/default/lwc/validationScreen/validationScreen.js-meta.xml
  force-app/main/default/objects/Survey_Setting__c/Survey_Setting__c.object-meta.xml
  force-app/main/default/objects/Survey_Setting__c/fields/Value__c.field-meta.xml
Labels: enhancement, refactor

#29 Bug/asp-7
  force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapper.cmp
  force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapper.cmp-meta.xml
  force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapper.design
  force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapperController.js
  force-app/main/default/classes/LookupController.cls
  force-app/main/default/classes/LookupControllerTest.cls
  force-app/main/default/classes/MetadataFetcher.cls
  force-app/main/default/classes/MetadataFetcherTest.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/customLookup/customLookup.html
  force-app/main/default/lwc/customLookup/customLookup.js
  force-app/main/default/lwc/customLookup/labels.js
  force-app/main/default/lwc/singleTriggerRule/helper.js
  force-app/main/default/lwc/singleTriggerRule/labels.js
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.html
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
  force-app/main/default/lwc/triggerRuleScreen/triggerRuleScreen.html
  force-app/main/default/lwc/triggerRuleScreen/triggerRuleScreen.js
  force-app/main/default/lwc/triggerRuleScreen/triggerRuleScreen.js-meta.xml
  force-app/main/default/lwc/triggerRulesWrapper/labels.js
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.html
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js
Labels: bug, refactor

#32 Bug/asp-42
  force-app/main/default/labels/CustomLabels.labels-meta.xml
Labels: bug

#31 Feature/asp 8
  force-app/main/default/classes/ChangedFieldWrapper.cls
  force-app/main/default/classes/ChangedFieldWrapper.cls-meta.xml
  force-app/main/default/classes/DateFieldComparator.cls
  force-app/main/default/classes/DateFieldComparator.cls-meta.xml
  force-app/main/default/classes/DateNumberFieldComparable.cls
  force-app/main/default/classes/DateNumberFieldComparable.cls-meta.xml
  force-app/main/default/classes/DateTimeFieldComparator.cls
  force-app/main/default/classes/DateTimeFieldComparator.cls-meta.xml
  force-app/main/default/classes/DecimalFieldComparator.cls
  force-app/main/default/classes/DecimalFieldComparator.cls-meta.xml
  force-app/main/default/classes/FieldComparable.cls
  force-app/main/default/classes/FieldComparable.cls-meta.xml
  force-app/main/default/classes/TestDataFactory.cls
  force-app/main/default/classes/TestDataFactory.cls-meta.xml
  force-app/main/default/classes/TextFieldComparable.cls
  force-app/main/default/classes/TextFieldComparable.cls-meta.xml
  force-app/main/default/classes/TextFieldComparator.cls
  force-app/main/default/classes/TextFieldComparator.cls-meta.xml
  force-app/main/default/classes/TriggerHandler.cls
  force-app/main/default/classes/TriggerHandler.cls-meta.xml
  force-app/main/default/classes/TriggerHandlerTest.cls
  force-app/main/default/classes/TriggerHandlerTest.cls-meta.xml
  force-app/main/default/classes/TriggerRulesHandler.cls
  force-app/main/default/classes/TriggerRulesHandler.cls-meta.xml
  force-app/main/default/globalValueSets/Operators.globalValueSet-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/listViews/All.listView-meta.xml
  force-app/main/default/triggers/CaseTrigger.trigger
  force-app/main/default/triggers/CaseTrigger.trigger-meta.xml
  force-app/main/default/triggers/ContactTrigger.trigger
  force-app/main/default/triggers/ContactTrigger.trigger-meta.xml
  force-app/main/default/triggers/LeadTrigger.trigger
  force-app/main/default/triggers/LeadTrigger.trigger-meta.xml
Labels: enhancement

#23 Feature/asp 5
  force-app/main/default/classes/ImageUploadController.cls
  force-app/main/default/classes/ImageUploadController.cls-meta.xml
  force-app/main/default/classes/ImageUploadControllerTest.cls
  force-app/main/default/classes/ImageUploadControllerTest.cls-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/basicScreen/basicScreen.css
  force-app/main/default/lwc/basicScreen/basicScreen.html
  force-app/main/default/lwc/basicScreen/basicScreen.js
  force-app/main/default/lwc/basicScreen/basicScreen.js-meta.xml
  force-app/main/default/lwc/basicScreen/labels.js
  force-app/main/default/lwc/imageUpload/imageUpload.css
  force-app/main/default/lwc/imageUpload/imageUpload.html
  force-app/main/default/lwc/imageUpload/imageUpload.js
  force-app/main/default/lwc/imageUpload/imageUpload.js-meta.xml
  force-app/main/default/lwc/imageUpload/labels.js
  force-app/main/default/objects/Survey__c/fields/Background_Color__c.field-meta.xml
  force-app/main/default/objects/Survey__c/validationRules/Color_check.validationRule-meta.xml
  force-app/main/default/permissionsets/Survey_Permission_Set.permissionset-meta.xml
Labels: enhancement

#34 fix: delete unnecessary metadata
  force-app/main/default/classes/DateNumberFieldComparable.cls
  force-app/main/default/classes/MetadataFetcher.cls
  force-app/main/default/classes/MetadataFetcherTest.cls
  force-app/main/default/classes/SurveySettingController.cls
  force-app/main/default/classes/SurveySettingControllerTest.cls
  force-app/main/default/classes/TextFieldComparable.cls
  force-app/main/default/flowDefinitions/Case_Survey_Initiator.flowDefinition-meta.xml
  force-app/main/default/flowDefinitions/Contact_Survey_Initiator.flowDefinition-meta.xml
  force-app/main/default/flowDefinitions/Lead_Survey_Initiator.flowDefinition-meta.xml
  force-app/main/default/flows/Case_Survey_Initiator.flow-meta.xml
  force-app/main/default/flows/Contact_Survey_Initiator.flow-meta.xml
  force-app/main/default/flows/Lead_Survey_Initiator.flow-meta.xml
  force-app/main/default/layouts/Answer__c-Answer Layout.layout-meta.xml
  force-app/main/default/layouts/Validation__c-Validation Layout.layout-meta.xml
  force-app/main/default/lwc/basicScreen/basicScreen.js-meta.xml
  force-app/main/default/lwc/formUtil/formUtil.js
  force-app/main/default/lwc/questionScreen/questionScreen.js-meta.xml
  force-app/main/default/lwc/singleTriggerRule/helper.js
  force-app/main/default/lwc/triggerRuleScreen/triggerRuleScreen.js-meta.xml
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.html
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js
  force-app/main/default/lwc/validationScreen/validationScreen.js
  force-app/main/default/lwc/validationScreen/validationScreen.js-meta.xml
  force-app/main/default/objects/Answer__c/fields/Body__c.field-meta.xml
  force-app/main/default/objects/Answer__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Validation__c/fields/Condition__c.field-meta.xml
Labels: documentation, metadata, refactor

#35 Feature/ASP-13
  force-app/main/default/dashboards/SurveyDashboard.dashboardFolder-meta.xml
  force-app/main/default/dashboards/SurveyDashboard/MainDashboard.dashboard-meta.xml
  force-app/main/default/globalValueSets/Operators.globalValueSet-meta.xml
  force-app/main/default/layouts/Survey__c-Survey Layout.layout-meta.xml
  force-app/main/default/lwc/questionScreen/questionScreen.js-meta.xml
  force-app/main/default/lwc/triggerRuleScreen/triggerRuleScreen.js-meta.xml
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js-meta.xml
  force-app/main/default/lwc/validationScreen/validationScreen.js-meta.xml
  force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
  force-app/main/default/objects/Email_Receiver__c/Email_Receiver__c.object-meta.xml
  force-app/main/default/objects/Group_Answer__c/Group_Answer__c.object-meta.xml
  force-app/main/default/objects/Question_Option__c/Question_Option__c.object-meta.xml
  force-app/main/default/objects/Question__c/Question__c.object-meta.xml
  force-app/main/default/objects/Related_Object__c/Related_Object__c.object-meta.xml
  force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
  force-app/main/default/objects/Survey__c/validationRules/Color_check.validationRule-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/Trigger_Rule__c.object-meta.xml
  force-app/main/default/objects/Validation__c/Validation__c.object-meta.xml
  force-app/main/default/permissionsets/Survey_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/Survey_Report_Dashboard_Permission_Set.permissionset-meta.xml
  force-app/main/default/reportTypes/Surveys.reportType-meta.xml
  force-app/main/default/reportTypes/Surveys_with_Email_Receivers.reportType-meta.xml
  force-app/main/default/reportTypes/Surveys_with_Questions_with_Answers.reportType-meta.xml
  force-app/main/default/reports/SurveyReport.reportFolder-meta.xml
  force-app/main/default/reports/SurveyReport/Surveys_Report.report-meta.xml
  force-app/main/default/reports/SurveyReport/Surveys_with_Email_Receivers_Report.report-meta.xml
  force-app/main/default/reports/SurveyReport/Surveys_with_QA_Report.report-meta.xml
  force-app/main/default/roles/Survey_Analysis_Team.role-meta.xml
  manifest/package.xml
Labels: documentation, duplicate, metadata

#36 Fix/asp-44
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/customLookup/customLookup.html
  force-app/main/default/lwc/singleTriggerRule/labels.js
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.html
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
  force-app/main/default/lwc/triggerRuleScreen/triggerRuleScreen.js
  force-app/main/default/lwc/triggerRulesFooterNavigation/triggerRulesFooterNavigation.html
  force-app/main/default/lwc/triggerRulesFooterNavigation/triggerRulesFooterNavigation.js
  force-app/main/default/lwc/triggerRulesFooterNavigation/triggerRulesFooterNavigation.js-meta.xml
  force-app/main/default/lwc/triggerRulesWrapper/labels.js
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js
Labels: enhancement, metadata, refactor

#37 documentation/ASP-22
  force-app/main/default/classes/SendEmailLogic.cls
  force-app/main/default/layouts/Email_Receiver__c-Email Receiver Layout.layout-meta.xml
  force-app/main/default/layouts/Group_Answer__c-Group Answer Layout.layout-meta.xml
  force-app/main/default/layouts/Question_Option__c-Question Option Layout.layout-meta.xml
  force-app/main/default/layouts/Question__c-Question Layout.layout-meta.xml
  force-app/main/default/layouts/Survey__c-Survey Layout.layout-meta.xml
  force-app/main/default/layouts/Trigger_Rule__c-Trigger Rule Layout.layout-meta.xml
  force-app/main/default/layouts/Validation__c-Validation Layout.layout-meta.xml
  force-app/main/default/lwc/questionForm/labels.js
  force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
  force-app/main/default/objects/Email_Receiver__c/Email_Receiver__c.object-meta.xml
  force-app/main/default/objects/Email_Receiver__c/fields/Value__c.field-meta.xml
  force-app/main/default/objects/Email_Receiver__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Group_Answer__c/Group_Answer__c.object-meta.xml
  force-app/main/default/objects/Group_Answer__c/fields/IsLinked__c.field-meta.xml
  force-app/main/default/objects/Group_Answer__c/fields/Related_To__c.field-meta.xml
  force-app/main/default/objects/Group_Answer__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Question_Option__c/Question_Option__c.object-meta.xml
  force-app/main/default/objects/Question__c/Question__c.object-meta.xml
  force-app/main/default/objects/Question__c/fields/IsVisible__c.field-meta.xml
  force-app/main/default/objects/Question__c/fields/Position__c.field-meta.xml
  force-app/main/default/objects/Question__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Related_Object__c/Related_Object__c.object-meta.xml
  force-app/main/default/objects/SurveyEmailConfig__c/SurveyEmailConfig__c.object-meta.xml
  force-app/main/default/objects/Survey_Setting__c/Survey_Setting__c.object-meta.xml
  force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
  force-app/main/default/objects/Survey__c/fields/Background_Color__c.field-meta.xml
  force-app/main/default/objects/Survey__c/fields/IsStandard__c.field-meta.xml
  force-app/main/default/objects/Survey__c/fields/Related_To__c.field-meta.xml
  force-app/main/default/objects/Survey__c/fields/URL__c.field-meta.xml
  force-app/main/default/objects/Survey__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/Trigger_Rule__c.object-meta.xml
  force-app/main/default/objects/Validation__c/Validation__c.object-meta.xml
  force-app/main/default/objects/Validation__c/fields/Dependent_Question__c.field-meta.xml
  force-app/main/default/objects/Validation__c/listViews/All.listView-meta.xml
  force-app/main/default/permissionsets/Survey_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/Survey_Report_Dashboard_Permission_Set.permissionset-meta.xml
  force-app/main/default/tabs/Answer__c.tab-meta.xml
  force-app/main/default/tabs/Email_Receiver__c.tab-meta.xml
  force-app/main/default/tabs/Group_Answer__c.tab-meta.xml
  force-app/main/default/tabs/Question_Option__c.tab-meta.xml
  force-app/main/default/tabs/Question__c.tab-meta.xml
  force-app/main/default/tabs/Related_Object__c.tab-meta.xml
  force-app/main/default/tabs/Survey__c.tab-meta.xml
  force-app/main/default/tabs/Trigger_Rule__c.tab-meta.xml
  force-app/main/default/tabs/Validation__c.tab-meta.xml
Labels: metadata, refactor

#40 feature/Asp-23
  force-app/main/default/applications/Survey.app-meta.xml
  force-app/main/default/aura/surveyConstructorLauncher/surveyConstructorLauncher.cmp
  force-app/main/default/aura/surveyConstructorLauncher/surveyConstructorLauncher.cmp-meta.xml
  force-app/main/default/aura/surveyConstructorLauncher/surveyConstructorLauncherController.js
  force-app/main/default/classes/SaverControllerTest.cls-meta.xml
  force-app/main/default/classes/SaverControllerTestDataFactory.cls-meta.xml
  force-app/main/default/flexipages/Survey_Constructor.flexipage-meta.xml
  force-app/main/default/flexipages/Survey_UtilityBar.flexipage-meta.xml
  force-app/main/default/lwc/saverScreen/saverScreen.js-meta.xml
  force-app/main/default/permissionsets/Survey_Permission_Set.permissionset-meta.xml
  force-app/main/default/tabs/Survey_Constructor.tab-meta.xml
  manifest/package.xml
Labels: documentation, enhancement, metadata

#43 refactor/ASP-23
  force-app/main/default/aura/surveyConstructorLauncher/surveyConstructorLauncher.cmp
  force-app/main/default/aura/surveyConstructorLauncher/surveyConstructorLauncherController.js
Labels: bug

#42 refactor/ASP-5
  force-app/main/default/classes/ImageDataWrapper.cls
  force-app/main/default/classes/ImageDataWrapper.cls-meta.xml
  force-app/main/default/classes/ImageUploadController.cls
  force-app/main/default/classes/ImageUploadControllerTest.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/basicScreen/basicScreen.html
  force-app/main/default/lwc/basicScreen/basicScreen.js
  force-app/main/default/lwc/basicScreen/basicScreen.js-meta.xml
  force-app/main/default/lwc/basicScreen/labels.js
  force-app/main/default/lwc/imageUpload/imageUpload.html
  force-app/main/default/lwc/imageUpload/imageUpload.js
  force-app/main/default/lwc/imageUpload/labels.js
Labels: enhancement, refactor

#38 Feature/asp 10
  force-app/main/default/classes/GroupController.cls
  force-app/main/default/classes/GroupController.cls-meta.xml
  force-app/main/default/classes/GroupControllerTest.cls
  force-app/main/default/classes/GroupControllerTest.cls-meta.xml
  force-app/main/default/classes/SurveyController.cls
  force-app/main/default/classes/SurveyControllerTest.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.css
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.html
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreenHelper.js
  force-app/main/default/lwc/advanceSettingScreen/labels.js
  force-app/main/default/lwc/questionScreen/questionScreen.js
  force-app/main/default/lwc/saverScreen/saverScreen.js
  force-app/main/default/lwc/saverScreen/saverScreen.js-meta.xml
Labels: enhancement

#41 Feature/asp-16
  force-app/main/default/classes/AnswerController.cls
  force-app/main/default/classes/AnswerController.cls-meta.xml
  force-app/main/default/classes/AnswerControllerTest.cls
  force-app/main/default/classes/AnswerControllerTest.cls-meta.xml
  force-app/main/default/classes/CustomExceptionData.cls
  force-app/main/default/classes/CustomExceptionData.cls-meta.xml
  force-app/main/default/classes/GroupAnswerController.cls
  force-app/main/default/classes/GroupAnswerController.cls-meta.xml
  force-app/main/default/classes/GroupAnswerControllerTest.cls
  force-app/main/default/classes/GroupAnswerControllerTest.cls-meta.xml
  force-app/main/default/classes/LookupController.cls
  force-app/main/default/classes/RelatedObjectController.cls
  force-app/main/default/classes/RelatedObjectController.cls-meta.xml
  force-app/main/default/classes/RelatedObjectControllerTest.cls
  force-app/main/default/classes/RelatedObjectControllerTest.cls-meta.xml
  force-app/main/default/classes/TestUtility.cls
  force-app/main/default/classes/TestUtility.cls-meta.xml
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
Labels: enhancement

#44 fix/ASP-5
  force-app/main/default/lwc/imageUpload/imageUpload.js
Labels: bug

#45 fix/ASP-5-1
  force-app/main/default/lwc/basicScreen/basicScreen.js
  force-app/main/default/lwc/imageUpload/imageUpload.html
  force-app/main/default/lwc/imageUpload/imageUpload.js
Labels: bug

#46 Feature/asp 31
  force-app/main/default/flowDefinitions/Survey_Flow.flowDefinition-meta.xml
  force-app/main/default/flows/Survey_Flow.flow-meta.xml
  force-app/main/default/lwc/basicScreen/basicScreen.js-meta.xml
  force-app/main/default/lwc/questionScreen/questionScreen.js-meta.xml
  force-app/main/default/lwc/triggerRuleScreen/triggerRuleScreen.js-meta.xml
  force-app/main/default/lwc/validationScreen/validationScreen.js-meta.xml
  manifest/package.xml
Labels: documentation, enhancement, metadata

#47 fix/bugs with questions and validations
  force-app/main/default/flows/Survey_Flow.flow-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/questionForm/labels.js
  force-app/main/default/lwc/questionForm/questionForm.html
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionForm/questionFormHelper.js
  force-app/main/default/lwc/validationForm/validationForm.html
  force-app/main/default/lwc/validationForm/validationForm.js
  force-app/main/default/lwc/validationScreen/labels.js
  force-app/main/default/lwc/validationScreen/validationScreen.js
  force-app/main/default/lwc/validationScreen/validationScreenHelper.js
Labels: bug

#48 fix: bugs with options
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionForm/questionFormHelper.js
  force-app/main/default/lwc/questionScreen/questionScreen.js
  force-app/main/default/lwc/questionScreen/questionScreenHelper.js
  force-app/main/default/lwc/saverScreen/saverScreen.js
  force-app/main/default/lwc/saverScreen/saverScreenHelper.js
Labels: bug

#49 Fix/bug-with-launch-button
  force-app/main/default/aura/surveyConstructorLauncher/surveyConstructorLauncher.cmp
  force-app/main/default/aura/surveyConstructorLauncher/surveyConstructorLauncherController.js
  force-app/main/default/classes/AnswerController.cls
  force-app/main/default/classes/AnswerControllerTest.cls
  force-app/main/default/classes/CustomExceptionData.cls
  force-app/main/default/classes/GroupAnswerController.cls
  force-app/main/default/classes/GroupAnswerControllerTest.cls
  force-app/main/default/classes/GroupController.cls
  force-app/main/default/classes/GroupControllerTest.cls
  force-app/main/default/classes/RelatedObjectController.cls
  force-app/main/default/classes/RelatedObjectControllerTest.cls
  force-app/main/default/classes/SurveyController.cls
  force-app/main/default/classes/TestUtility.cls
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.css
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.html
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreenHelper.js
  force-app/main/default/lwc/advanceSettingScreen/labels.js
Labels: bug

#50 fix/update-permission-sets
  force-app/main/default/aura/surveyConstructorLauncher/surveyConstructorLauncher.cmp
  force-app/main/default/permissionsets/Admin_Survey_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/User_Survey_Permission_Set.permissionset-meta.xml
  manifest/package.xml
Labels: documentation, metadata, refactor

#51 fix/add fields to related lists
  force-app/main/default/layouts/Question__c-Question Layout.layout-meta.xml
  force-app/main/default/layouts/Survey__c-Survey Layout.layout-meta.xml
  force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
  force-app/main/default/objects/Email_Receiver__c/Email_Receiver__c.object-meta.xml
  force-app/main/default/objects/Group_Answer__c/Group_Answer__c.object-meta.xml
  force-app/main/default/objects/Question_Option__c/Question_Option__c.object-meta.xml
  force-app/main/default/objects/Question__c/Question__c.object-meta.xml
  force-app/main/default/objects/Related_Object__c/Related_Object__c.object-meta.xml
  force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/Trigger_Rule__c.object-meta.xml
  force-app/main/default/objects/Validation__c/Validation__c.object-meta.xml
Labels: documentation, metadata, refactor

#52 Refactor/add-pop-up-logic
  force-app/main/default/aura/surveyConstructor/surveyConstructor.cmp
  force-app/main/default/aura/surveyConstructor/surveyConstructor.cmp-meta.xml
  force-app/main/default/aura/surveyConstructor/surveyConstructorController.js
  force-app/main/default/aura/surveyConstructorLauncher/surveyConstructorLauncher.cmp
  force-app/main/default/aura/surveyConstructorLauncher/surveyConstructorLauncherController.js
  force-app/main/default/labels/CustomLabels.labels-meta.xml
Labels: enhancement, refactor

#53 Fix/main bugs on trigger rules screen
  force-app/main/default/classes/SurveySettingController.cls
  force-app/main/default/classes/SurveySettingControllerTest.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/customLookup/customLookup.js
  force-app/main/default/lwc/singleTriggerRule/helper.js
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
  force-app/main/default/lwc/triggerRulesWrapper/helper.js
  force-app/main/default/lwc/triggerRulesWrapper/labels.js
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.html
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js
Labels: bug, metadata, refactor

#54 Fix/change-custom-setting-type
  force-app/main/default/objects/SurveyEmailConfig__c/SurveyEmailConfig__c.object-meta.xml
Labels: metadata, refactor

#58 Refactor/asp 47
  force-app/main/default/classes/AnswerControllerTest.cls
  force-app/main/default/classes/QuestionControllerTest.cls
  force-app/main/default/classes/SaverControllerTest.cls
  force-app/main/default/classes/SaverControllerTestDataFactory.cls
  force-app/main/default/classes/SurveySettingController.cls
  force-app/main/default/classes/SurveySettingControllerTest.cls
  force-app/main/default/flows/Survey_Flow.flow-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/formUtil/formUtil.js
  force-app/main/default/lwc/questionBar/labels.js
  force-app/main/default/lwc/questionBar/questionBar.html
  force-app/main/default/lwc/questionBar/questionBar.js
  force-app/main/default/lwc/questionBar/questionBar.js-meta.xml
  force-app/main/default/lwc/questionBar/questionBarHelper.js
  force-app/main/default/lwc/questionCard/labels.js
  force-app/main/default/lwc/questionCard/questionCard.html
  force-app/main/default/lwc/questionCard/questionCard.js
  force-app/main/default/lwc/questionForm/labels.js
  force-app/main/default/lwc/questionForm/questionForm.html
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionForm/questionFormHelper.js
  force-app/main/default/lwc/questionScreen/labels.js
  force-app/main/default/lwc/questionScreen/questionScreen.html
  force-app/main/default/lwc/questionScreen/questionScreen.js
  force-app/main/default/lwc/questionScreen/questionScreen.js-meta.xml
  force-app/main/default/lwc/questionScreen/questionScreenHelper.js
  force-app/main/default/lwc/questionSearch/questionSearch.css
  force-app/main/default/lwc/questionSearch/questionSearch.html
  force-app/main/default/lwc/questionSearch/questionSearch.js
  force-app/main/default/lwc/questionSearchItem/questionSearchItem.html
  force-app/main/default/lwc/questionSearchItem/questionSearchItem.js
  force-app/main/default/lwc/questionStandardSelector/labels.js
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelector.html
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelector.js
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelector.js-meta.xml
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelectorHelper.js
  force-app/main/default/lwc/questionsBlock/labels.js
  force-app/main/default/lwc/questionsBlock/questionsBlock.html
  force-app/main/default/lwc/questionsBlock/questionsBlock.js
  force-app/main/default/lwc/questionsBlock/questionsBlock.js-meta.xml
  force-app/main/default/lwc/questionsBlock/questionsBlockHelper.js
  force-app/main/default/lwc/validationCard/labels.js
  force-app/main/default/lwc/validationCard/validationCard.css
  force-app/main/default/lwc/validationCard/validationCard.html
  force-app/main/default/lwc/validationCard/validationCard.js
  force-app/main/default/lwc/validationForm/labels.js
  force-app/main/default/lwc/validationForm/validationForm.html
  force-app/main/default/lwc/validationForm/validationForm.js
  force-app/main/default/lwc/validationForm/validationForm.js-meta.xml
  force-app/main/default/lwc/validationForm/validationFormHelper.js
  force-app/main/default/lwc/validationScreen/labels.js
  force-app/main/default/lwc/validationScreen/validationScreen.html
  force-app/main/default/lwc/validationScreen/validationScreen.js
  force-app/main/default/lwc/validationScreen/validationScreen.js-meta.xml
  force-app/main/default/lwc/validationScreen/validationScreenHelper.js
  force-app/main/default/objects/Question__c/fields/Position__c.field-meta.xml
Labels: metadata, refactor

#57 Fix/add description field
  force-app/main/default/aura/surveyConstructor/surveyConstructor.cmp
  force-app/main/default/aura/surveyConstructor/surveyConstructorController.js
  force-app/main/default/flows/Survey_Flow.flow-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.html
  force-app/main/default/lwc/basicScreen/basicScreen.css
  force-app/main/default/lwc/basicScreen/basicScreen.html
  force-app/main/default/lwc/basicScreen/basicScreen.js
  force-app/main/default/lwc/basicScreen/labels.js
  force-app/main/default/lwc/screenHeader/screenHeader.html
  force-app/main/default/lwc/screenHeader/screenHeader.js
  force-app/main/default/lwc/screenHeader/screenHeader.js-meta.xml
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.html
Labels: metadata, refactor

#59 Refactor/email-logic
  force-app/main/default/classes/CampaignController.cls
  force-app/main/default/classes/CampaignController.cls-meta.xml
  force-app/main/default/classes/ChangedFieldWrapper.cls
  force-app/main/default/classes/SendEmailLogic.cls
  force-app/main/default/classes/SendEmailLogicHelper.cls
  force-app/main/default/classes/SendEmailLogicHelper.cls-meta.xml
  force-app/main/default/classes/SendEmailLogicTest.cls
  force-app/main/default/classes/TriggerHandler.cls
  force-app/main/default/classes/TriggerHandlerTest.cls
  force-app/main/default/classes/TriggerRulesHandler.cls
  force-app/main/default/classes/searchHelper.cls
  force-app/main/default/classes/searchHelper.cls-meta.xml
  force-app/main/default/dashboards/SurveyDashboard/MainDashboard.dashboard-meta.xml
  force-app/main/default/flows/Survey_Flow.flow-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/layouts/Email_Receiver__c-Email Receiver Layout.layout-meta.xml
  force-app/main/default/layouts/Survey__c-Survey Layout.layout-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.css
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.html
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreenHelper.js
  force-app/main/default/lwc/advanceSettingScreen/labels.js
  force-app/main/default/lwc/saverScreen/saverScreen.js
  force-app/main/default/objects/Email_Receiver__c/Email_Receiver__c.object-meta.xml
  force-app/main/default/objects/Email_Receiver__c/fields/IsSend__c.field-meta.xml
  force-app/main/default/objects/Email_Receiver__c/fields/Type__c.field-meta.xml
  force-app/main/default/objects/Email_Receiver__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
  force-app/main/default/objects/Survey__c/fields/IsResending__c.field-meta.xml
  force-app/main/default/objects/Survey__c/listViews/All.listView-meta.xml
  force-app/main/default/permissionsets/Admin_Survey_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/Survey_Report_Dashboard_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/User_Survey_Permission_Set.permissionset-meta.xml
  force-app/main/default/reportTypes/Surveys.reportType-meta.xml
  force-app/main/default/reportTypes/Surveys_with_Email_Receivers.reportType-meta.xml
  force-app/main/default/reportTypes/Surveys_with_Questions_with_Answers.reportType-meta.xml
  force-app/main/default/reports/SurveyReport/Surveys_with_Email_Receivers_Report.report-meta.xml
Labels: documentation, enhancement, metadata, refactor

#60 Feature/asp 50
  force-app/main/default/lwc/questionCard/questionCard.html
  force-app/main/default/lwc/questionCard/questionCard.js
  force-app/main/default/lwc/questionForm/questionForm.html
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionForm/questionFormHelper.js
  force-app/main/default/lwc/questionScreen/questionScreen.html
  force-app/main/default/lwc/questionScreen/questionScreen.js
  force-app/main/default/lwc/questionScreen/questionScreenHelper.js
  force-app/main/default/lwc/questionStandardSelector/labels.js
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelector.js
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelectorHelper.js
  force-app/main/default/lwc/questionsBlock/questionsBlock.js
Labels: bug, enhancement

#61 Fix/email-logic-bugs
  force-app/main/default/flows/Survey_Flow.flow-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.html
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreenHelper.js
  force-app/main/default/lwc/advanceSettingScreen/labels.js
  force-app/main/default/lwc/questionBar/questionBar.js-meta.xml
  force-app/main/default/lwc/questionScreen/questionScreen.js-meta.xml
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelector.js-meta.xml
  force-app/main/default/lwc/questionsBlock/questionsBlock.js-meta.xml
  force-app/main/default/lwc/saverScreen/saverScreen.js
  force-app/main/default/lwc/screenHeader/screenHeader.js-meta.xml
  force-app/main/default/permissionsets/Admin_Survey_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/Survey_Report_Dashboard_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/User_Survey_Permission_Set.permissionset-meta.xml
Labels: bug, documentation, metadata, refactor

#62 Feature/asp-49
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/confirmationPopup/confirmationPopup.css
  force-app/main/default/lwc/confirmationPopup/confirmationPopup.html
  force-app/main/default/lwc/confirmationPopup/confirmationPopup.js
  force-app/main/default/lwc/confirmationPopup/confirmationPopup.js-meta.xml
  force-app/main/default/lwc/questionCard/labels.js
  force-app/main/default/lwc/questionCard/questionCard.html
  force-app/main/default/lwc/questionCard/questionCard.js
  force-app/main/default/lwc/questionScreen/questionScreen.html
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.html
Labels: enhancement, metadata, refactor
