Repository DunaevViktor/VJV-Survey, pull requests merged in 2021-02, with the labels that each got.

#63 Fix/asp 55
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/questionForm/labels.js
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionForm/questionFormHelper.js
  force-app/main/default/lwc/questionScreen/questionScreen.html
  force-app/main/default/lwc/questionScreen/questionScreen.js
  force-app/main/default/lwc/questionScreen/questionScreenHelper.js
  force-app/main/default/lwc/questionsBlock/labels.js
  force-app/main/default/lwc/questionsBlock/questionsBlock.js
  force-app/main/default/lwc/questionsBlock/questionsBlockHelper.js
Labels: bug, refactor

#64 Refactor/trigger rules screen bugs
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/triggerRulesWrapper/labels.js
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.html
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js
Labels: metadata, refactor

#66 Fix/fix basic screen issues
  force-app/main/default/classes/ImageUploadControllerTest.cls
  force-app/main/default/lwc/basicScreen/basicScreen.html
  force-app/main/default/lwc/basicScreen/basicScreen.js
Labels: bug, refactor

#68 Refactor/asp 51
  force-app/main/default/classes/AnswerControllerTest.cls
  force-app/main/default/classes/CampaignControllerTest.cls
  force-app/main/default/classes/CampaignControllerTest.cls-meta.xml
  force-app/main/default/classes/GroupAnswerControllerTest.cls
  force-app/main/default/classes/GroupControllerTest.cls
  force-app/main/default/classes/ImageUploadControllerTest.cls
  force-app/main/default/classes/LookupControllerTest.cls
  force-app/main/default/classes/MetadataFetcher.cls
  force-app/main/default/classes/QuestionControllerTest.cls
  force-app/main/default/classes/RelatedObjectControllerTest.cls
  force-app/main/default/classes/SaverControllerTest.cls
  force-app/main/default/classes/SaverControllerTestDataFactory.cls
  force-app/main/default/classes/SearchHelper.cls
  force-app/main/default/classes/SearchHelper.cls-meta.xml
  force-app/main/default/classes/SearchHelperTest.cls
  force-app/main/default/classes/SearchHelperTest.cls-meta.xml
  force-app/main/default/classes/SendEmailLogicTest.cls
  force-app/main/default/classes/SurveyControllerTest.cls
  force-app/main/default/classes/SurveySettingControllerTest.cls
  force-app/main/default/classes/TestDataFactory.cls
  force-app/main/default/classes/TestUtility.cls
  force-app/main/default/classes/TriggerHandlerTest.cls
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingSreenHelper.js
Labels: refactor

#65 Fix/bug-from-59-and-61-pr
  force-app/main/default/classes/SendEmailLogic.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.html
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreenHelper.js
  force-app/main/default/lwc/advanceSettingScreen/labels.js
  force-app/main/default/lwc/confirmationPopup/confirmationPopup.js-meta.xml
Labels: bug, metadata, refactor

#69 Fix/advance-setting-screen-lwc
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingSreenHelper.js
Labels: bug

#67 Feature/asp 15
  force-app/main/default/classes/AnswerFormController.cls
  force-app/main/default/classes/AnswerFormController.cls-meta.xml
  force-app/main/default/classes/AnswerFormControllerTest.cls
  force-app/main/default/classes/AnswerFormControllerTest.cls-meta.xml
  force-app/main/default/classes/RelatedObjectController.cls
  force-app/main/default/classes/RelatedObjectControllerTest.cls
  force-app/main/default/classes/SaverController.cls
  force-app/main/default/flexipages/Survey_Answer_Form.flexipage-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.html
  force-app/main/default/lwc/answerForm/answerForm.css
  force-app/main/default/lwc/answerForm/answerForm.html
  force-app/main/default/lwc/answerForm/answerForm.js
  force-app/main/default/lwc/answerForm/answerForm.js-meta.xml
  force-app/main/default/lwc/answerForm/answerFormHelper.js
  force-app/main/default/lwc/answerForm/labels.js
  force-app/main/default/lwc/formUtil/formUtil.js
  force-app/main/default/lwc/saverScreen/saverScreen.js
  force-app/main/default/lwc/singleQuestion/singleQuestion.html
  force-app/main/default/lwc/singleQuestion/singleQuestion.js
  force-app/main/default/lwc/singleQuestion/singleQuestion.js-meta.xml
  force-app/main/default/lwc/starRatingInput/starRatingInput.css
  force-app/main/default/lwc/starRatingInput/starRatingInput.html
  force-app/main/default/lwc/starRatingInput/starRatingInput.js
  force-app/main/default/lwc/starRatingInput/starRatingInput.js-meta.xml
  force-app/main/default/objects/Validation__c/fields/Dependent_Question__c.field-meta.xml
  force-app/main/default/objects/Validation__c/fields/Related_Question__c.field-meta.xml
  force-app/main/default/permissionsets/Admin_Survey_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/User_Survey_Permission_Set.permissionset-meta.xml
  force-app/main/default/tabs/Survey_Answer_Form.tab-meta.xml
  manifest/package.xml
Labels: enhancement, metadata, refactor

#70 Refactor/asp 60
  force-app/main/default/globalValueSets/Object_Api_Names.globalValueSet-meta.xml
  force-app/main/default/lwc/basicScreen/basicScreen.html
  force-app/main/default/lwc/questionScreen/labels.js
  force-app/main/default/lwc/questionScreen/questionScreenHelper.js
  force-app/main/default/lwc/saverScreen/saverScreen.css
  force-app/main/default/lwc/saverScreen/saverScreen.html
  force-app/main/default/lwc/saverSpinner/saverSpinner.css
  force-app/main/default/lwc/saverSpinner/saverSpinner.html
  force-app/main/default/lwc/saverSpinner/saverSpinner.js
  force-app/main/default/lwc/saverSpinner/saverSpinner.js-meta.xml
  force-app/main/default/objects/Trigger_Rule__c/fields/Object_Api_Name__c.field-meta.xml
Labels: bug, refactor

#71 Feature/asp-54
  force-app/main/default/classes/MetadataFetcher.cls
  force-app/main/default/classes/MetadataFetcherTest.cls
  force-app/main/default/classes/PostInstallConfig.cls
  force-app/main/default/classes/PostInstallConfig.cls-meta.xml
  force-app/main/default/classes/PostInstallConfigTest.cls
  force-app/main/default/classes/PostInstallConfigTest.cls-meta.xml
  force-app/main/default/classes/SurveySettingController.cls
  force-app/main/default/classes/SurveySettingControllerTest.cls
  force-app/main/default/lwc/basicScreen/basicScreen.js
  force-app/main/default/objects/Survey_Setting__c/fields/Background_Color__c.field-meta.xml
  force-app/main/default/objects/Survey_Setting__c/fields/Max_Question_Amount__c.field-meta.xml
  force-app/main/default/objects/Survey_Setting__c/fields/Max_Trigger_Rule_Amount__c.field-meta.xml
  force-app/main/default/objects/Survey_Setting__c/fields/Min_Question_Amount__c.field-meta.xml
  force-app/main/default/objects/Survey_Setting__c/fields/Page_Question_Amount__c.field-meta.xml
Labels: enhancement, metadata, refactor

#72 Fix/asp 62
  force-app/main/default/lwc/questionForm/questionForm.js
Labels: bug

#73 Feature/asp-63
  force-app/main/default/classes/FieldDescriptionWrapper.cls
  force-app/main/default/classes/FieldDescriptionWrapper.cls-meta.xml
  force-app/main/default/classes/MetadataFetcher.cls
  force-app/main/default/classes/MetadataFetcherTest.cls
  force-app/main/default/lwc/singleTriggerRule/helper.js
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
  manifest/package.xml
Labels: metadata, refactor

#74 Refactor/send-email-logic
  force-app/main/default/classes/CampaignController.cls
  force-app/main/default/classes/CampaignControllerTest.cls
  force-app/main/default/classes/GroupController.cls
  force-app/main/default/classes/SearchHelperTest.cls
  force-app/main/default/classes/SendEmailLogic.cls
  force-app/main/default/classes/SendEmailLogicHelper.cls
  force-app/main/default/classes/SendEmailLogicTest.cls
  force-app/main/default/email/SurveyTemplates/HTML_Template.email
  force-app/main/default/email/SurveyTemplates/HTML_Template.email-meta.xml
  force-app/main/default/email/SurveyTemplates/Main_Template.email
  force-app/main/default/email/SurveyTemplates/Main_Template.email-meta.xml
  force-app/main/default/letterhead/SurveyLetterhead.letter-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js
  force-app/main/default/lwc/answerForm/answerForm.js-meta.xml
  manifest/package.xml
Labels: documentation, enhancement, metadata, refactor

#75 Refactor/asp 65
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.css
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.html
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreenHelper.js
  force-app/main/default/lwc/advanceSettingScreen/labels.js
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionStandardSelector/labels.js
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelector.css
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelector.html
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelector.js
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelectorHelper.js
Labels: bug, enhancement, refactor

#77 Refactor/asp 68
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.html
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreenHelper.js
  force-app/main/default/lwc/advanceSettingScreen/labels.js
  force-app/main/default/lwc/questionForm/labels.js
  force-app/main/default/lwc/questionForm/questionForm.html
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionStandardSelector/labels.js
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelector.html
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelector.js
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelectorHelper.js
  force-app/main/default/lwc/questionsBlock/questionsBlock.js
Labels: bug, refactor

#78 fix/bug-with-questions-screen
  force-app/main/default/lwc/questionCard/questionCard.html
  force-app/main/default/lwc/questionCard/questionCard.js
  force-app/main/default/lwc/questionsBlock/labels.js
  force-app/main/default/lwc/questionsBlock/questionsBlock.html
  force-app/main/default/lwc/questionsBlock/questionsBlock.js
  force-app/main/default/lwc/questionsBlock/questionsBlockHelper.js
Labels: bug, refactor

#56 feature/ASP-48
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/questionForm/labels.js
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/translations/ru.translation-meta.xml
  manifest/package.xml
Labels: documentation, enhancement, metadata, refactor

#76 Feature/asp 58
  force-app/main/default/flows/Survey_Flow.flow-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/answerForm/answerForm.html
  force-app/main/default/lwc/previewScreen/labels.js
  force-app/main/default/lwc/previewScreen/previewScreen.css
  force-app/main/default/lwc/previewScreen/previewScreen.html
  force-app/main/default/lwc/previewScreen/previewScreen.js
  force-app/main/default/lwc/previewScreen/previewScreen.js-meta.xml
  force-app/main/default/lwc/previewScreen/previewScreenHelper.js
  force-app/main/default/lwc/singleQuestion/singleQuestion.html
  force-app/main/default/lwc/singleQuestion/singleQuestion.js
  force-app/main/default/lwc/starRatingInput/starRatingInput.js
  force-app/main/default/translations/ru.translation-meta.xml
  manifest/package.xml
Labels: enhancement, metadata

#82 Fix/asp 64
  force-app/main/default/lwc/answerForm/answerForm.js
  force-app/main/default/lwc/answerForm/answerFormHelper.js
  force-app/main/default/lwc/answerForm/labels.js
  force-app/main/default/lwc/previewScreen/previewScreenHelper.js
  force-app/main/default/lwc/singleQuestion/singleQuestion.html
  force-app/main/default/lwc/singleQuestion/singleQuestion.js
Labels: bug, enhancement, refactor

#83 Refactor/ASP-45
  force-app/main/default/classes/AnswerControllerTest.cls
  force-app/main/default/classes/AnswerFormControllerTest.cls
  force-app/main/default/classes/CampaignControllerTest.cls
  force-app/main/default/classes/GroupAnswerControllerTest.cls
  force-app/main/default/classes/GroupControllerTest.cls
  force-app/main/default/classes/ImageUploadControllerTest.cls
  force-app/main/default/classes/LookupController.cls
  force-app/main/default/classes/LookupControllerTest.cls
  force-app/main/default/classes/MetadataFetcherTest.cls
  force-app/main/default/classes/PostInstallConfigTest.cls
  force-app/main/default/classes/QuestionControllerTest.cls
  force-app/main/default/classes/RelatedObjectControllerTest.cls
  force-app/main/default/classes/SaverControllerTest.cls
  force-app/main/default/classes/SearchHelperTest.cls
  force-app/main/default/classes/SendEmailLogicTest.cls
  force-app/main/default/classes/SurveyControllerTest.cls
  force-app/main/default/classes/SurveySettingControllerTest.cls
  force-app/main/default/classes/TestDataFactory.cls
  force-app/main/default/classes/TriggerHandlerTest.cls
Labels: bug, refactor

#85 Feature/ASP-70
  force-app/main/default/classes/QuestionController.cls
  force-app/main/default/classes/QuestionControllerTest.cls
  force-app/main/default/classes/QuestionWrapper.cls
  force-app/main/default/classes/QuestionWrapper.cls-meta.xml
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.html
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreen.js
  force-app/main/default/lwc/advanceSettingScreen/advanceSettingScreenHelper.js
  force-app/main/default/lwc/answerForm/answerForm.html
  force-app/main/default/lwc/answerForm/answerForm.js
  force-app/main/default/lwc/answerForm/answerFormHelper.js
  force-app/main/default/lwc/answerForm/labels.js
  force-app/main/default/lwc/basicScreen/basicScreen.html
  force-app/main/default/lwc/basicScreen/basicScreen.js
  force-app/main/default/lwc/fieldService/fieldService.js
  force-app/main/default/lwc/fieldService/fieldService.js-meta.xml
  force-app/main/default/lwc/formUtil/formUtil.js
  force-app/main/default/lwc/optionListElement/optionListElement.html
  force-app/main/default/lwc/optionListElement/optionListElement.js
  force-app/main/default/lwc/previewScreen/previewScreen.html
  force-app/main/default/lwc/previewScreen/previewScreen.js
  force-app/main/default/lwc/previewScreen/previewScreenHelper.js
  force-app/main/default/lwc/questionBar/questionBarHelper.js
  force-app/main/default/lwc/questionCard/questionCard.html
  force-app/main/default/lwc/questionCard/questionCard.js
  force-app/main/default/lwc/questionForm/questionForm.html
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionForm/questionFormHelper.js
  force-app/main/default/lwc/questionScreen/questionScreen.js
  force-app/main/default/lwc/questionScreen/questionScreenHelper.js
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelector.js
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelectorHelper.js
  force-app/main/default/lwc/questionsBlock/questionsBlock.html
  force-app/main/default/lwc/questionsBlock/questionsBlock.js
  force-app/main/default/lwc/questionsBlock/questionsBlockHelper.js
  force-app/main/default/lwc/saverScreen/saverScreen.js
  force-app/main/default/lwc/saverScreen/saverScreenHelper.js
  force-app/main/default/lwc/singleQuestion/singleQuestion.html
  force-app/main/default/lwc/singleQuestion/singleQuestion.js
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
  force-app/main/default/lwc/starRatingInput/starRatingInput.html
  force-app/main/default/lwc/starRatingInput/starRatingInput.js
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js
Labels: bug, refactor

#84 Feature/asp-67
  force-app/main/default/classes/TriggerRulesHandler.cls
  force-app/main/default/globalValueSets/Operators.globalValueSet-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/confirmationPopup/confirmationPopup.html
  force-app/main/default/lwc/formUtil/formUtil.js
  force-app/main/default/lwc/questionCard/questionCard.html
  force-app/main/default/lwc/questionForm/questionFormHelper.js
  force-app/main/default/lwc/singleTriggerRule/labels.js
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.css
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.html
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
  force-app/main/default/lwc/triggerRulesWrapper/helper.js
  force-app/main/default/lwc/triggerRulesWrapper/labels.js
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.html
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js
  force-app/main/default/objects/Trigger_Rule__c/fields/Field_Value__c.field-meta.xml
  force-app/main/default/translations/ru.translation-meta.xml
Labels: bug, metadata, refactor

#80 feature/asp 71
  force-app/main/default/layouts/Group_Answer__c-Group Answer Layout.layout-meta.xml
  force-app/main/default/layouts/Question__c-Question Layout.layout-meta.xml
  force-app/main/default/layouts/Related_Object__c-Related Object Layout.layout-meta.xml
  force-app/main/default/layouts/Survey__c-Survey Layout.layout-meta.xml
Labels: documentation, metadata, refactor

#86 Fix/asp 81
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionsBlock/questionsBlock.js
  force-app/main/default/lwc/questionsBlock/questionsBlockHelper.js
Labels: bug

#81 feature/asp 4
  force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
  force-app/main/default/permissionsets/Admin_Survey_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/Survey_Admin_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/Survey_Creator_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/Survey_User_Permission_Set.permissionset-meta.xml
Labels: metadata, refactor

#88 fix/bugs with basic screen
  force-app/main/default/flows/Survey_Flow.flow-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/basicScreen/basicScreen.html
  force-app/main/default/lwc/basicScreen/basicScreen.js
  force-app/main/default/lwc/basicScreen/basicScreen.js-meta.xml
  force-app/main/default/lwc/basicScreen/basicScreenHelper.js
  force-app/main/default/lwc/basicScreen/labels.js
  force-app/main/default/lwc/emailSettingsScreen/emailSettingsScreen.css
  force-app/main/default/lwc/emailSettingsScreen/emailSettingsScreen.html
  force-app/main/default/lwc/emailSettingsScreen/emailSettingsScreen.js
  force-app/main/default/lwc/emailSettingsScreen/emailSettingsScreen.js-meta.xml
  force-app/main/default/lwc/emailSettingsScreen/emailSettingsScreenHelper.js
  force-app/main/default/lwc/emailSettingsScreen/labels.js
  force-app/main/default/translations/ru.translation-meta.xml
Labels: bug

#89 Fix/asp 74
  force-app/main/default/aura/answerFormWrapper/answerFormWrapper.cmp
  force-app/main/default/aura/answerFormWrapper/answerFormWrapper.cmp-meta.xml
  force-app/main/default/aura/answerFormWrapper/answerFormWrapperController.js
  force-app/main/default/classes/AnswerFormController.cls
  force-app/main/default/classes/QuestionWrapper.cls
  force-app/main/default/classes/SaverController.cls
  force-app/main/default/classes/SaverControllerTest.cls
  force-app/main/default/flexipages/Survey_Answer_Form.flexipage-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/answerForm/answerForm.css
  force-app/main/default/lwc/answerForm/answerForm.js
  force-app/main/default/lwc/answerForm/answerFormHelper.js
  force-app/main/default/lwc/answerForm/labels.js
  force-app/main/default/lwc/saverScreen/constants.js
  force-app/main/default/lwc/saverScreen/saverScreen.js
  force-app/main/default/translations/ru.translation-meta.xml
  manifest/package.xml
Labels: refactor

#87 Feature/asp-77
  config/project-scratch-def.json
  force-app/main/default/classes/AnswerFormController.cls
  force-app/main/default/classes/CampaignController.cls
  force-app/main/default/classes/GroupController.cls
  force-app/main/default/classes/NamespaceService.cls
  force-app/main/default/classes/NamespaceService.cls-meta.xml
  force-app/main/default/classes/QuestionController.cls
  force-app/main/default/classes/RelatedObjectController.cls
  force-app/main/default/classes/SendEmailLogicHelper.cls
  force-app/main/default/classes/SurveyController.cls
  force-app/main/default/permissionsets/Survey_Admin_Permission_Set.permissionset-meta.xml
Labels: enhancement, metadata, refactor

#90 refactor/ASP-73
  force-app/main/default/aura/answerFormWrapper/answerFormWrapper.cmp
  force-app/main/default/aura/answerFormWrapper/answerFormWrapper.cmp-meta.xml
  force-app/main/default/aura/answerFormWrapper/answerFormWrapperController.js
  force-app/main/default/classes/NamespaceService.cls
  force-app/main/default/classes/QuestionWrapper.cls
  force-app/main/default/dashboards/SurveyDashboard.dashboardFolder-meta.xml
  force-app/main/default/flows/Survey_Flow.flow-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/basicScreen/labels.js
  force-app/main/default/lwc/emailSettingsScreen/emailSettingsScreen.css
  force-app/main/default/lwc/emailSettingsScreen/emailSettingsScreen.html
  force-app/main/default/lwc/emailSettingsScreen/emailSettingsScreen.js
  force-app/main/default/lwc/emailSettingsScreen/emailSettingsScreen.js-meta.xml
  force-app/main/default/lwc/emailSettingsScreen/emailSettingsScreenHelper.js
  force-app/main/default/lwc/emailSettingsScreen/labels.js
  force-app/main/default/lwc/fieldService/fieldService.js
  force-app/main/default/lwc/fieldService/fieldService.js-meta.xml
  force-app/main/default/permissionsets/Survey_Creator_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/Survey_Report_Dashboard_Permission_Set.permissionset-meta.xml
  force-app/main/default/permissionsets/Survey_User_Permission_Set.permissionset-meta.xml
  force-app/main/default/reports/SurveyReport.reportFolder-meta.xml
  force-app/main/default/roles/Survey_Analysis_Team.role-meta.xml
  force-app/main/default/translations/ru.translation-meta.xml
  manifest/package.xml
Labels: bug, metadata, refactor

#92 Feature/asp-86
  force-app/main/default/classes/PostInstallConfigTest.cls
  force-app/main/default/classes/SurveySettingController.cls
  force-app/main/default/classes/SurveySettingControllerTest.cls
  force-app/main/default/objects/SurveyEmailConfig__c/SurveyEmailConfig__c.object-meta.xml
  force-app/main/default/objects/Survey_Setting__c/Survey_Setting__c.object-meta.xml
  force-app/main/default/objects/Survey_Setting__c/fields/Community_Name__c.field-meta.xml
  force-app/main/default/objects/Survey_Setting__c/fields/Min_Question_Amount__c.field-meta.xml
Labels: metadata, refactor

#93 Fix/asp 4
  force-app/main/default/permissionsets/Survey_User_Permission_Set.permissionset-meta.xml
Labels: metadata, refactor

#95 fix/asp-4_2
  force-app/main/default/permissionsets/Survey_User_Permission_Set.permissionset-meta.xml
Labels: metadata, refactor

#94 Refactor/asp 84
  force-app/main/default/classes/SearchHelper.cls
  force-app/main/default/classes/TriggerRulesHandler.cls
  force-app/main/default/lwc/answerForm/answerForm.js
  force-app/main/default/lwc/answerForm/answerFormHelper.js
  force-app/main/default/lwc/basicScreen/basicScreen.js
  force-app/main/default/lwc/customLookup/customLookup.js
  force-app/main/default/lwc/emailSettingsScreen/emailSettingsScreen.js
  force-app/main/default/lwc/emailSettingsScreen/emailSettingsScreenHelper.js
  force-app/main/default/lwc/imageUpload/imageUpload.js
  force-app/main/default/lwc/optionListElement/optionListElement.js
  force-app/main/default/lwc/previewScreen/previewScreen.js
  force-app/main/default/lwc/previewScreen/previewScreenHelper.js
  force-app/main/default/lwc/questionCard/questionCard.js
  force-app/main/default/lwc/questionForm/questionForm.js
  force-app/main/default/lwc/questionForm/questionFormHelper.js
  force-app/main/default/lwc/questionScreen/questionScreen.js
  force-app/main/default/lwc/questionScreen/questionScreenHelper.js
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelector.js
  force-app/main/default/lwc/questionStandardSelector/questionStandardSelectorHelper.js
  force-app/main/default/lwc/questionsBlock/questionsBlock.js
  force-app/main/default/lwc/questionsBlock/questionsBlockHelper.js
  force-app/main/default/lwc/saverScreen/saverScreen.js
  force-app/main/default/lwc/saverScreen/saverScreenHelper.js
  force-app/main/default/lwc/singleTriggerRule/helper.js
  force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
  force-app/main/default/lwc/starRatingInput/starRatingInput.js
  force-app/main/default/lwc/triggerRulesWrapper/helper.js
  force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js
Labels: refactor

#96 Feature/asp-87
  force-app/main/default/classes/AnswerController.cls
  force-app/main/default/classes/GroupAnswerController.cls
  force-app/main/default/classes/MetadataFetcherTest.cls
  force-app/main/default/classes/NamespaceService.cls
  force-app/main/default/classes/RelatedObjectController.cls
  force-app/main/default/classes/RelatedObjectControllerTest.cls
  force-app/main/default/classes/SendEmailLogicTest.cls
  force-app/main/default/classes/TestDataFactory.cls
  force-app/main/default/classes/TriggerHandlerTest.cls
Labels: refactor
